[package]
name = "window_debug"
version = "0.1.0"
authors = ["edward"]
edition = "2021"

[features]
centered_text = []

[dependencies]
minifb = { version = "0.23", default-features = false, features = ["wayland", "dlopen"] }
